// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room_event.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Msg {

  #region Messages
  public sealed class UserElement : pb::IMessage {
    private static readonly pb::MessageParser<UserElement> _parser = new pb::MessageParser<UserElement>(() => new UserElement());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserElement> Parser { get { return _parser; } }

    /// <summary>Field number for the "imei_hmacsha256" field.</summary>
    public const int ImeiHmacsha256FieldNumber = 1;
    private string imeiHmacsha256_ = "";
    /// <summary>
    ///hmacsha256 加密的最优 imei
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ImeiHmacsha256 {
      get { return imeiHmacsha256_; }
      set {
        imeiHmacsha256_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "persona_id" field.</summary>
    public const int PersonaIdFieldNumber = 2;
    private string personaId_ = "";
    /// <summary>
    ///hmacsha256 加密的最优 imei
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PersonaId {
      get { return personaId_; }
      set {
        personaId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "up_id" field.</summary>
    public const int UpIdFieldNumber = 3;
    private string upId_ = "";
    /// <summary>
    ///设备唯一号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UpId {
      get { return upId_; }
      set {
        upId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 4;
    private string gender_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Gender {
      get { return gender_; }
      set {
        gender_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 5;
    private string age_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Age {
      get { return age_; }
      set {
        age_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "residence" field.</summary>
    public const int ResidenceFieldNumber = 6;
    private string residence_ = "";
    /// <summary>
    ///常驻省份（湖南省、广东省。。。）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Residence {
      get { return residence_; }
      set {
        residence_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "residence_city" field.</summary>
    public const int ResidenceCityFieldNumber = 7;
    private string residenceCity_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ResidenceCity {
      get { return residenceCity_; }
      set {
        residenceCity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "up_constellation_up" field.</summary>
    public const int UpConstellationUpFieldNumber = 8;
    private string upConstellationUp_ = "";
    /// <summary>
    ///星座（金牛座、白羊座。。。）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UpConstellationUp {
      get { return upConstellationUp_; }
      set {
        upConstellationUp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "active_date_dev" field.</summary>
    public const int ActiveDateDevFieldNumber = 9;
    private string activeDateDev_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ActiveDateDev {
      get { return activeDateDev_; }
      set {
        activeDateDev_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "inactive_date_dev" field.</summary>
    public const int InactiveDateDevFieldNumber = 10;
    private string inactiveDateDev_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string InactiveDateDev {
      get { return inactiveDateDev_; }
      set {
        inactiveDateDev_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cp_dev" field.</summary>
    public const int CpDevFieldNumber = 11;
    private string cpDev_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CpDev {
      get { return cpDev_; }
      set {
        cpDev_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "brand_dev" field.</summary>
    public const int BrandDevFieldNumber = 12;
    private string brandDev_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BrandDev {
      get { return brandDev_; }
      set {
        brandDev_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "os" field.</summary>
    public const int OsFieldNumber = 13;
    private string os_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Os {
      get { return os_; }
      set {
        os_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "android_ver_dev" field.</summary>
    public const int AndroidVerDevFieldNumber = 14;
    private string androidVerDev_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AndroidVerDev {
      get { return androidVerDev_; }
      set {
        androidVerDev_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ios_ver_dev" field.</summary>
    public const int IosVerDevFieldNumber = 15;
    private string iosVerDev_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IosVerDev {
      get { return iosVerDev_; }
      set {
        iosVerDev_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ImeiHmacsha256.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ImeiHmacsha256);
      }
      if (PersonaId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PersonaId);
      }
      if (UpId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(UpId);
      }
      if (Gender.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Gender);
      }
      if (Age.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Age);
      }
      if (Residence.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Residence);
      }
      if (ResidenceCity.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ResidenceCity);
      }
      if (UpConstellationUp.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(UpConstellationUp);
      }
      if (ActiveDateDev.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(ActiveDateDev);
      }
      if (InactiveDateDev.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(InactiveDateDev);
      }
      if (CpDev.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(CpDev);
      }
      if (BrandDev.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(BrandDev);
      }
      if (Os.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Os);
      }
      if (AndroidVerDev.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(AndroidVerDev);
      }
      if (IosVerDev.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(IosVerDev);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ImeiHmacsha256.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImeiHmacsha256);
      }
      if (PersonaId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PersonaId);
      }
      if (UpId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UpId);
      }
      if (Gender.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Gender);
      }
      if (Age.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Age);
      }
      if (Residence.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Residence);
      }
      if (ResidenceCity.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResidenceCity);
      }
      if (UpConstellationUp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UpConstellationUp);
      }
      if (ActiveDateDev.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ActiveDateDev);
      }
      if (InactiveDateDev.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InactiveDateDev);
      }
      if (CpDev.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CpDev);
      }
      if (BrandDev.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BrandDev);
      }
      if (Os.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Os);
      }
      if (AndroidVerDev.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AndroidVerDev);
      }
      if (IosVerDev.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IosVerDev);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            ImeiHmacsha256 = input.ReadString();
            break;
          }
          case 18: {
            PersonaId = input.ReadString();
            break;
          }
          case 26: {
            UpId = input.ReadString();
            break;
          }
          case 34: {
            Gender = input.ReadString();
            break;
          }
          case 42: {
            Age = input.ReadString();
            break;
          }
          case 50: {
            Residence = input.ReadString();
            break;
          }
          case 58: {
            ResidenceCity = input.ReadString();
            break;
          }
          case 66: {
            UpConstellationUp = input.ReadString();
            break;
          }
          case 74: {
            ActiveDateDev = input.ReadString();
            break;
          }
          case 82: {
            InactiveDateDev = input.ReadString();
            break;
          }
          case 90: {
            CpDev = input.ReadString();
            break;
          }
          case 98: {
            BrandDev = input.ReadString();
            break;
          }
          case 106: {
            Os = input.ReadString();
            break;
          }
          case 114: {
            AndroidVerDev = input.ReadString();
            break;
          }
          case 122: {
            IosVerDev = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed class ActionElement : pb::IMessage {
    private static readonly pb::MessageParser<ActionElement> _parser = new pb::MessageParser<ActionElement>(() => new ActionElement());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ActionElement> Parser { get { return _parser; } }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private string uid_ = "";
    /// <summary>
    ///用户 id,
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Uid {
      get { return uid_; }
      set {
        uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_city" field.</summary>
    public const int UserCityFieldNumber = 2;
    private string userCity_ = "";
    /// <summary>
    /// 用户所在城市，
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserCity {
      get { return userCity_; }
      set {
        userCity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "item_id" field.</summary>
    public const int ItemIdFieldNumber = 3;
    private string itemId_ = "";
    /// <summary>
    /// 作品 id,
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ItemId {
      get { return itemId_; }
      set {
        itemId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "author_id" field.</summary>
    public const int AuthorIdFieldNumber = 4;
    private string authorId_ = "";
    /// <summary>
    ///作者 id,
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AuthorId {
      get { return authorId_; }
      set {
        authorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "item_city" field.</summary>
    public const int ItemCityFieldNumber = 5;
    private string itemCity_ = "";
    /// <summary>
    ///作者城市，
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ItemCity {
      get { return itemCity_; }
      set {
        itemCity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "channel" field.</summary>
    public const int ChannelFieldNumber = 6;
    private string channel_ = "";
    /// <summary>
    ///观看到该作品的来源，
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Channel {
      get { return channel_; }
      set {
        channel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "item_cate" field.</summary>
    public const int ItemCateFieldNumber = 7;
    private string itemCate_ = "";
    /// <summary>
    ///作品类别，
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ItemCate {
      get { return itemCate_; }
      set {
        itemCate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "finish" field.</summary>
    public const int FinishFieldNumber = 8;
    private string finish_ = "";
    /// <summary>
    ///是否浏览完作品，
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Finish {
      get { return finish_; }
      set {
        finish_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "like" field.</summary>
    public const int LikeFieldNumber = 9;
    private string like_ = "";
    /// <summary>
    ///是否对作品点赞，
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Like {
      get { return like_; }
      set {
        like_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "device" field.</summary>
    public const int DeviceFieldNumber = 10;
    private string device_ = "";
    /// <summary>
    ///设备 id,
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Device {
      get { return device_; }
      set {
        device_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 11;
    private string time_ = "";
    /// <summary>
    ///（track1:作品观看起始时间，track2:作品发布时间），
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Time {
      get { return time_; }
      set {
        time_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "duration_time" field.</summary>
    public const int DurationTimeFieldNumber = 12;
    private string durationTime_ = "";
    /// <summary>
    ///作品时长
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DurationTime {
      get { return durationTime_; }
      set {
        durationTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Uid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uid);
      }
      if (UserCity.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserCity);
      }
      if (ItemId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ItemId);
      }
      if (AuthorId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AuthorId);
      }
      if (ItemCity.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ItemCity);
      }
      if (Channel.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Channel);
      }
      if (ItemCate.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ItemCate);
      }
      if (Finish.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Finish);
      }
      if (Like.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Like);
      }
      if (Device.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Device);
      }
      if (Time.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Time);
      }
      if (DurationTime.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(DurationTime);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Uid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
      }
      if (UserCity.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserCity);
      }
      if (ItemId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemId);
      }
      if (AuthorId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthorId);
      }
      if (ItemCity.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemCity);
      }
      if (Channel.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Channel);
      }
      if (ItemCate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemCate);
      }
      if (Finish.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Finish);
      }
      if (Like.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Like);
      }
      if (Device.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Device);
      }
      if (Time.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Time);
      }
      if (DurationTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DurationTime);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Uid = input.ReadString();
            break;
          }
          case 18: {
            UserCity = input.ReadString();
            break;
          }
          case 26: {
            ItemId = input.ReadString();
            break;
          }
          case 34: {
            AuthorId = input.ReadString();
            break;
          }
          case 42: {
            ItemCity = input.ReadString();
            break;
          }
          case 50: {
            Channel = input.ReadString();
            break;
          }
          case 58: {
            ItemCate = input.ReadString();
            break;
          }
          case 66: {
            Finish = input.ReadString();
            break;
          }
          case 74: {
            Like = input.ReadString();
            break;
          }
          case 82: {
            Device = input.ReadString();
            break;
          }
          case 90: {
            Time = input.ReadString();
            break;
          }
          case 98: {
            DurationTime = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
